spring:
  datasource:
#    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5432/catsdb
    url: jdbc:postgresql://${DATASOURCE_HOST}/${DB_NAME}
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver


#  spring.jpa.hibernate.ddl-auto=update
#  spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#  spring.jpa.properties.hibernate.format_sql=true
#  spring.jpa.show-sql=true

server:
  port: 8082

springdoc:
  swagger-ui:
    path=/swagger-ui.html