apiVersion: v1
kind: Service
metadata:
  name: cats-db
  labels:
    run: cats-db
spec:
  type: NodePort
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: cats-db