apiVersion: apps/v1
kind: Deployment
metadata:
  name: cats-api
  labels:
    app: cats-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cats-api
  template:
    metadata:
      labels:
        app: cats-api
    spec:
      containers:
        - name: cats-api
          image: olegvn88/cat:0.0.1
          imagePullPolicy: "Always"
#          resources:
#            limits:
#              cpu: 1
#              memory: 100Mi
#              ephemeral-storage: 200Mi
          ports:
            - containerPort: 8082
          env:
            - name: DATASOURCE_HOST
              value: cats-db
            - name: spring.mvc.servlet.path
              value: /cats-api
            - name: DB_NAME
              value: catsdb
      automountServiceAccountToken: false