apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.databaseName }}-{{ .Release.Name }}-secret
  labels:
    app: {{ .Values.databaseName }}-{{ .Release.Name }}
data:
  POSTGRES_DB: catsdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.databaseName }}-{{ .Release.Name }}-volume
  labels:
    type: local
    app: {{ .Values.databaseName }}-{{ .Release.Name }}
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.databaseName }}-{{ .Release.Name }}-volume-claim
  labels:
    app: {{ .Values.databaseName }}-{{ .Release.Name }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.databaseName }}-{{ .Release.Name }}
  labels:
    app: {{ .Values.databaseName }}-{{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.databaseName }}-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.databaseName }}-{{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.databaseName }}-{{ .Release.Name }}
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "1"
              memory: 100Mi
              ephemeral-storage: 200Mi
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: {{ .Values.databaseName }}-{{ .Release.Name }}-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      automountServiceAccountToken: false
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: {{ .Values.databaseName }}-{{ .Release.Name }}-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.databaseName }}-{{ .Release.Name }}
  labels:
    run: {{ .Values.databaseName }}-{{ .Release.Name }}
spec:
  type: NodePort
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: {{ .Values.databaseName }}-{{ .Release.Name }}