# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "test variable"
        default: 'dev'
        options:
          - sbx
          - tst
          - dev
  workflow_call:
    inputs:
      foo:
        type: string
        default: 'dev'
      git_ref:
        required: true
        type: string
jobs:
  functional-test:
    runs-on: ubuntu-latest
    name: Func tests ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          ref: ${{ inputs.git_ref }}

      - name: Set up JDK 11
        uses: ./.github/actions/functional_tests.yml
        with:
          branch: ${{ github.ref_name }}
          environment: dev


