name: "Deploy: Continuous Deployment to DEV"
run-name: Create release from ${{ github.ref_name }} and deploy to Dev
on:
  push:
    branches:
      - master

jobs:
  setTagName:
    name: 'Set tag name'
    runs-on: 'ubuntu-latest'
    outputs:
      tagName: ${{ steps.set_tag.outputs.tagName }}
    steps:
      - name: 'Validate & Set a tag name'
        id: set_tag
        run: |
          echo "Hello setTagName";
          
          if [[ ${{ github.ref_name }} == main ]]; then
              echo "main branch"
              export TAG_NAME="release_v0.0.${{ github.run_number }}"
              # Output the TAG_NAME to GitHub Actions output
              echo "tagName=$TAG_NAME" >> $GITHUB_OUTPUT

              for release in $(echo "$releases" | jq -r '.[] | @base64'); do
                  name=$(echo "$release" | base64 -d | jq -r '.name')
                  draft=$(echo "$release" | base64 -d | jq -r '.draft')
    
                  if [ "$draft" == "true" ] && [[ "$name" == *patch* ]]; then
                      echo "Hotfix/Patch Draft release: $name is active on dev environment..."
                      exit 1
                  fi
              done

  build-publish-image:
    name: "Build & Publish"
    needs: [ setTagName ]
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.ref_name }}
      tag_name: ${{ needs.setTagName.outputs.tagName }}
    secrets: inherit

  functional-test:
    name: "Functional Test"
    needs: [ build-publish-image ]
    uses: ./.github/workflows/run_tests.yml
    with:
      environment: "dev"
      git_ref: ${{ github.sha }}
    secrets: inherit