name: Run at 9:35 AM Ukraine Time

on:
  schedule:
    - cron: '36 6 * * *'

jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - run: |
          date -u
          echo "This job runs at 09:27 Ukraine time (06:35 UTC)"