name: Run tests

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        description: name or var
        type: string
  workflow_call:
    inputs:
      name:
        required: true
        description: name or var
        type: string
  schedule:
    - cron: '45 10 * * *'

jobs:
  run-task:
    name: Run every at time
    runs-on: ubuntu-latest
    env:
      ENV1: env1
      ENV2: env2++
    steps:
      - run: |
          date -u
          echo "This job runs at date -u with variable - ${{ inputs.name }}"
          echo "Name - ${{ env.ENV1 }} works"
          echo "Hello - $ENV2 working"
