name: Run at 9:35 AM Ukraine Time

on:
  schedule:
    - cron: '/5 * * * *'

jobs:
  run-task:
    name: Run every 5 minutes
    runs-on: ubuntu-latest
    steps:
      - run: |
          date -u
          echo "This job runs at 09:27 Ukraine time (06:35 UTC)"