name: Run tests

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        description: name or var
        type: string
  workflow_call:
    inputs:
      name:
        required: true
        description: name or var
        type: string
  schedule:
    - cron: '45 10 * * *'

jobs:
  run-task:
    name: Run every at time
    runs-on: ubuntu-latest
    steps:
      - run: |
          date -u
          echo "This job runs at date -u with variable - ${{ inputs.name }}"
