name: Run tests

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        description: name or var
        type: string
  workflow_call:
    inputs:
      name:
        required: true
        description: name or var
        type: string
  schedule:
    - cron: '15 8 * * *'

jobs:
  run-task:
    if: ${{ (inputs.name == null || 'regression') == 'regression' }}
    name: Run every at time
    runs-on: ubuntu-latest
    env:
      ENV1: env1
      ENV2: env2++
    steps:
      - name:
        env:
          name: name
        run: |
          date -u
          echo "This job runs at date -u with variable - ${{ inputs.name }}"
          echo "Name - ${{ env.ENV1 }} works"
          echo "Hello - $ENV2 working"
          echo "Hello - ${{ env.name }} hi"
