name: Run at 10:50 AM Ukraine Time

on:
  schedule:
    - cron: '50 7 * * *'

jobs:
  run-task:
    name: Run every at time
    runs-on: ubuntu-latest
    steps:
      - run: |
          date -u
          echo "This job runs at date -u Ukraine time date -u"