name: "Functional Test Run"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: choice
        default: "dev"
        required: true
        options:
          - sbx
          - dev
          - psrtest
          - tst
      foo:
        default: "foooooo-workflow_dispatch"
        required: false
        description: "foo"
        type: string

  workflow_call:
    inputs:
      environment:
        description: "The environment where the functional test will point out."
        default: "dev"
        required: true
        type: string
      git_ref:
        required: true
        description: desc git_ref
        type: string
      foo:
        default: "foooooo"
        required: false
        description: "foo"
        type: string
  schedule:
    - cron: '*/5 * * * *'
jobs:
  repo-job:
    name: Func tests on - ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: "override"
    steps:
      - name: print param
        run: |
          echo "${{ inputs.foo }} - ${{ inputs.environment }} - ${{ inputs.git_ref }}"